Mappings:
  AWSRegions:
    ap-south-1:
      AMI: ami-02913db388613c3e1
      Instance: t2.micro
      DBInstance: db.t2.micro
    ap-southeast-1:
      AMI: ami-048a01c78f7bae4aa
      Instance: t2.micro
      DBInstance: db.t2.micro
    ap-southeast-2:
      AMI: ami-03ed5bd63ba378bd8
      Instance: t2.micro
      DBInstance: db.t2.micro
    ap-northeast-1:
      AMI: ami-0ab3e16f9c414dee7
      Instance: t2.micro
      DBInstance: db.t2.micro
    ap-east-1:
      AMI: ami-d3e992a2
      Instance: t3.micro
      DBInstance: db.t3.micro
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [AWSRegions, !Ref "AWS::Region", DBInstance] # Dynamic mapping + Pseudo Parameter
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: w0rdpr355
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Fn::FindInMap:
         - AWSRegions
         - !Ref AWS::Region
         - AMI
      InstanceType:  
        Fn::FindInMap:
         - AWSRegions
         - !Ref AWS::Region
         - Instance
  S3:
    Type: "AWS::S3::Bucket"
# As bucket name is static and must be unique globally. To create S3 bucket with unique name we need to comment below code. Hence, S3 Bucket will be unique globally.
#    Properties:
#      BucketName: wp-s3bucket18092019
# End