Mappings:
  MyRegionMap: # Retrieved in Line 18
    ap-south-1:
      AMI: ami-02913db388613c3e1
    ap-southeast-1:
      AMI: ami-048a01c78f7bae4aa
    ap-southeast-2:
      AMI: ami-03ed5bd63ba378bd8
    ap-northeast-1:
      AMI: ami-0ab3e16f9c414dee7
    ap-east-1:
      AMI: ami-d3e992a2
Resources:
  Ec2Instance: # Logical Id 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId:  # Demo of Mappings
        Fn::FindInMap:
        - MyRegionMap
        - !Ref AWS::Region
        - AMI
      Tags: # PseudoParameters - !Ref AWS::Region / !Ref AWS::StackName
        - 
          Key: Name
          Value: !Join 
            - " "
            - - Ec2 Instance is created in 
              - !Ref AWS::Region
        - 
          Key: Department
          Value: !Ref AWS::StackName
      SecurityGroups: 
        - !Ref MyInstanceSG # Reference to Security Group. CF Template recognises this reference and invokes Line 13 for Security Group Creation first, followed by EC2 Instance Creation 
  MyInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Access via port 22
      SecurityGroupIngress: 
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0